# Clean portable DT1 profile.  Account, password, bank-PIN, session and
# machine-specific state are intentionally excluded.
detuksinferno.debug=true
detuksfightcave.enabled=false
runelite.allureaccountbuilder=false
runelite.colosseumplugin=false
runelite.fightcaveplugin=false
runelite.infernoplugin=false
runelite.fishing=false
runelite.clientSidebarClosed=false
runelite.gameSize=765x503
runelite.automaticResizeType=KEEP_GAME_SIZE
detuksclient.disableLinkBrowser=true
